### PR TITLE
Added placeholder image

### PR DESCRIPTION
**Pull request by JonathanSpeek**

### CODE REVIEW

**Comment by pjhampton** [comment]
Wow! Nice work @JonathanSpeek!! And thank you 👍 

I will accept this on the first of October so it actually counts! I will ping you when I do

References: #14

**Comment by JonathanSpeek** [comment]
Thanks, cheers!

**Comment by pjhampton** [comment]
Sorry @JonathanSpeek, I got the name wrong, it is called `screenshot.png` andd should be 1200x900 pixels. Would you mind changing it?

https://codex.wordpress.org/Theme_Development#Screenshot

**Comment by JonathanSpeek** [comment]
@pjhampton I've made the changes you requested. Let me know if you need anything else.

**Comment by pjhampton** [comment]
Thanks @JonathanSpeek!! You rock!

Will merge this on Saturday

💙  ❤️  💛

**Comment by pjhampton** [comment]
Hey @JonathanSpeek 

Can you please close and reopen a new PR please? Hacktoberfest requires you to have _opened_ the PR in October, not just accepted in October. I don't want you to lose your credit.

**Pull request closed without merging**
