### PR TITLE
Merge pull request #1 from pjhampton/master

### PR DESCRIPTION
**Pull request by manuelmdn**
Add desgin to checkout and order detail pages

### CODE REVIEW

**Comment by pjhampton** [comment]
Thanks for doing that @manuelmdn. I screwed up the last merge

💛  💙  ❤️  💜  💚

**Comment by manuelmdn** [comment]
hehehe ok, don't worry, I'll follow repository issues and help if you need, srry my bad english 😅

**Comment by pjhampton** [comment]
It actually seems that there was no files changed in this commit. Can you please try again? Sorry for this hassle!

**Comment by pjhampton** [comment]
Actually, I think the best thing to do, is to:

1) `git clone https://github.com/pjhampton/bigbooty bigbooty_fix`
2) `cd bigbooty_fix`
3) `git branch -b readdo_commits`
4) Add all your old files back in
5) `git commit -m "Adding checkout files."`
6) `git push`
7) send a PR.

Sorry, sending the PR to another branch screwed all this up, but it's not your fault, it's mine. Hopefully this isn't annoying you but you have put so much work in and I want you to get the credit.

**Pull request merged**
