### PR TITLE
Added bootstrap styling for Password Protected form, references: #38

### PR DESCRIPTION
**Pull request by Bobeta**
References: #38 Hope it suits the needs that you requested :)

skarmavbild 2016-10-09 kl 17 03 51

### CODE REVIEW

**Comment by pjhampton** [comment]
Thanks @Bobeta. This is perfect. Can you just please update your message and I will merge it?

**Comment by Bobeta** [comment]
Glad you like it! I just updated the message :)

**Comment by pjhampton** [comment]
Thanks again @Bobeta 💛  ❤️  💙

**Comment by Bobeta** [comment]
You're welcome mate! 💓

**Pull request merged**
